name: Android-Publishment-build
on:
  push:
    branches: [main]

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - name: Setup Flutter Credential
        run: flutter pub get
      - name: Run Flutter test
        run: flutter test
      - name: Build Release apk
        run: flutter build apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path:
            build/app/outputs/flutter-apk/app-release.apk