name: Android-Development-build
on: [push, pull_request]

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - name: Setup Flutter Credential
        run: flutter pub get
      - name: Run Flutter test
        run: flutter test
      - name: Build Debug apk
        run: flutter build apk --debug
      - name: Build Debug appbundle
        run: flutter build appbundle --debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debug-artifacts
          path:
            build/app/outputs/flutter/*debug.apk
            build/app/outputs/bundle/debug/*.aab

  build-release-apk:
    if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - name: Setup Flutter Credential
        run: flutter pub get
      - name: Run Flutter test
        run: flutter test
      - name: Build Release apk
        run: flutter build apk
      - name: Build Release appbundle
        run: flutter build appbundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path:
            build/app/outputs/flutter-apk/*release.apk
            build/app/outputs/bundle/release/*.aab
